### ISSUE TITLE
Niveaus van WCAG-succescriteria weergeven op pagina's

### ISSUE THREAD

**Issue by hidde** [nl-design-system/documentatie#1022]
We hebben (denk ik bewust?) gekozen om geen niveaus (A/AA/AAA) weer te geven op [richtlijnenpagina's (voorbeeld)](https://nldesignsystem.nl/wcag/1.1.1). 

Wettelijk zijn alleen SC's van specifieke niveaus verplicht (A/AA), het is daarom denk ik aannemelijk dat mensen willen weten welke 'verplicht' zijn en welke niet. Ik zou dus voorstellen toch de niveau's te noemen.

**Comment by rianrietveld** [comment]
@hidde: Dit was een bewuste keuze van Robbert.

@Robbert wat was jouw motivatie hiervoor?

**Comment by MarjonBakker** [comment]
Er staat nu op elke WCAG-pagina een label achter de h1, kan dit issue gesloten worden?

**Comment by rianrietveld** [comment]
ja! Ik sluit um, tnx @MarjonBakker 
Opgelost via de issue https://github.com/nl-design-system/documentatie/issues/1304 en #1315
