### ISSUE TITLE
Focus Trap issue in Sidebar Navigation

### ISSUE THREAD

**Issue by savitris** [nl-design-system/documentatie#1024]
# Focus Trap issue in Sidebar Navigation

**Pagina:** [Elke pagina van de NL Design System website](https://www.nldesignsystem.nl/)

**Probleem:** De NL Design System website heeft een Main Navigation (zie Afbeelding 1) die bij inzoomen verandert in een Sidebar Navigation (zie Afbeelding 2). Het probleem is dat wanneer de gebruiker dit Sidebar Navigation opent (zie Afbeelding 3), de focus zich gedurende twee tabstops buiten het menu bevindt (zie Afbeeldingen 4, 5 en 6). Pas na de derde tabstop komt de focus binnen in het Sidebar Navigation en kan de gebruiker door elk item erin tabben. Wanneer de focus zich op het laatste item van het Sidebar Navigation bevindt en de gebruiker opnieuw op de Tab-toets drukt, verplaatst de focus zich buiten het Sidebar Navigation zonder dat het zichzelf sluit (zie Afbeelding 7). Hierdoor kan de Toetsenbord-gebruiker niet zien waar de Focus-ring zich bevindt. 

**Extra:** 
Op elke andere pagina dan de homepage, als voorbeeld de [Componenten Pagina](https://nldesignsystem.nl/componenten/)  zien we hetzelfde Focus Trap Issue. Maar na uiteindelijk de focus binnen de Sidebar Navigation te hebben verplaatst, krijgt de eerste component die focus krijgt de Hoofdmenu-knop, daarna de X-knop en vervolgens gaat de focus weer buiten de Sidebar Navigation naar de links van de Main Navigation, dit zonder de focus te verplaatsen naar de sectie van de Sidebar Navigation die deze links bevat.

Ten slotte, na opnieuw te tabben, komen we weer in de Sidebar Navigation op de Overzicht-link en kunnen we door elk van de items in de Componenten-sectie van de Sidebar Navigation tabben.

Tabben na het laatste item in de Componenten-sectie van de Sidebar Navigation verplaatst de focus opnieuw buiten de Sidebar Navigation (op de "Home" link) zonder deze te sluiten.

**Gerelateerde afbeeldingen:**

Afbeelding 1
![Screenshot 2024-06-18 at 17 20 43](https://github.com/nl-design-system/backlog/assets/11764984/0fe3ce09-b899-4834-a9f3-9555d42b999b)
---
Afbeelding 2
![Screenshot 2024-06-18 at 17 26 14](https://github.com/nl-design-system/backlog/assets/11764984/8dc00273-7808-470e-8066-fa054d1415ed)
---
Afbeelding 3
![Screenshot 2024-06-18 at 17 12 28](https://github.com/nl-design-system/backlog/assets/11764984/e85e7444-8a41-424a-b05b-331dbecf2b27)
--
Afbeelding 4
![Screenshot 2024-06-18 at 17 10 30](https://github.com/nl-design-system/backlog/assets/11764984/503590a2-7f2a-4d7f-9170-2f96ef88caac)
--
Afbeelding 5
![Screenshot 2024-06-18 at 17 10 41](https://github.com/nl-design-system/backlog/assets/11764984/1c9cb051-34da-4854-a0b1-086ab3ee0a59)
--
Afbeelding 6
![Screenshot 2024-06-18 at 17 09 50](https://github.com/nl-design-system/backlog/assets/11764984/9236d518-075f-46bf-8cb6-b04dd937c23e)
--
Afbeelding 7
![Screenshot 2024-06-18 at 17 12 28](https://github.com/nl-design-system/backlog/assets/11764984/13e68b2f-2b74-4947-a0e6-bc6525d7c6da)
--

**WCAG Succes Criteria:**
2.4.3 Focus Order
2.1.2 No Keyboard Trap
3.2.1 On Focus

**Comment by rianrietveld** [comment]
@savitris Dank voor het melden!

**Comment by hidde** [comment]
Dank voor de uitgebreide omschrijving, heel fijn. 

ls ik het goed begrijp is er juist geen focus trap, het probleem is dat het niet getrapt wordt waardoor focus buiten de navigatie kan komen, wat niet te bedoeling is, want dan is die onzichtbaar en daarmee onbruikbaar. Daarmee is dit hetzelfde issue als #413.
