### ISSUE TITLE
Richtlijnen/ WCAG-pagina's: "Skip link" in navigation landmark of in banner landmark?

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1065]
Zie: https://nldesignsystem.nl/wcag/2.4.1

Nu staat er in de documentatie:

> Sommige validatiesoftware meldt dat een skiplink binnen een landmark moet staan. Hierover zijn de meningen verdeeld. Het plaatsen van een skiplink binnen een landmark is in ieder geval geen voorwaarde om aan WCAG te voldoen.

Laten we mensen een oplossing bieden. En laten we nog een uitvraag doen wat mensen er van denken.

Something to consider: de skip link niet helemaal buiten de layout plaatsen op een groot scherm, in de page header zou beter opvallen.

**Comment by rianrietveld** [comment]
@hidde @Robbert 
Na wat nader onderzoek denk ik dat we moeten adviseren de skiplink binnen de header landmark te plaasten.

Als een gebruiker via landmarks navigeert mist deze de skiplink niet.

Bij denhaag.nl en utrecht.nl staat de skiplink nu ook in de header.

Sommige validatiesoftware (zoals axe DevTools) geven aan dat alle content binnen een landmark hoort. Om verwarring te voorkomen is het beter om deze lijn te volgen.

In het [Web Accessibility Cookbook](https://www.oreilly.com/library/view/web-accessibility-cookbook/9781098145590/) beveelt Manuel Matuzovic ook aan om de skiplink binnen de header te zetten. Zodat alle content binnen een landmark staat.

Mijn suggestie:
Aanbevelen binnen de landmark, maar erbuiten is geen WCAG-overtreding.

Ik pas de tekst op twee plekken aan:

Bij de uitleg:
Oud:
> Om zo gebruikersvriendelijk en consistent mogelijk te werken is een skiplink de eerste link op een pagina. Het eerste focusable element, en staat deze zichtbaar linksboven op een vaste plek.

Nieuw:
> Om zo gebruikersvriendelijk en consistent mogelijk te werken is een skiplink de eerste link op een pagina. Plaats deze link binnen de header-landmark. Als eerste focusable element, bovenaan de pagina, op een vaste plek.

Bij het testen:
Oud:
> Het plaatsen van een skiplink binnen de header- landmark is _best practice_. Maar, staat de skiplink bovenaan de pagina als eerste focusable element en buiten een landmark, dat is dit **geen** overtreding van dit WCAG-succescriterium.
