### ISSUE TITLE
Richtlijnen: Een pagina per richtlijn, verzamelpagina's met link behouden

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#1068]
Op dit moment hebben we de richtlijnen op verzamepagina's staan, gegroepeerd op onderwerp.
Nu we steeds meer informatie bij de richtlijnen schrijven gaat deze wringen, de pagina's worden erg lang.
Een pagina per richtlijn komt de leesbaarheid en flexibiliteit ten goede.

Daarnaast zijn de link naar de richtlijnen nu afhankelijk van het h2 kopje van de richtlijn. Het nadeel hiervan is dat lelijke en lange urls oplevert.
Yolijn gaf aan dat je de ID van een kopje kunt overrulen door er een gekozen ID dussen brackets achter te zetten.
Good to know! Zie: https://github.com/nl-design-system/documentatie/blob/main/docs/componenten/paragraph/_guidelines.md
Bijvoorbeeld: Paragraph {#paragraph}

Mijn voorstel:
- Elke richtlijn krijgt een eigen pagina met een systematische url.
- We houden de verzamelpagina's intact. Dan blijkt ook de introductie op een logische plek.
- In plaats van interne links (naar de pagina zelf), linken we nu extern naar de afzonderlijke richtlijnen.
- Op de pagina van een afzonderlinke richtlijn staat dan alle info, belangrijk is om ook terug te kunnen linken naar de hoofdpagina.
- De oude (interne) urls worden geredirect naar de nieuwe.

Vraag: is het mogelijk 'hoofdpagina' op te nemen in het kruimelpad?  
Bijvoorbeeld:  
Home - Richtlijnen - Formulieren - Buttons - Toetsenbordbediening
Of is dat _too much_?

**Comment by rianrietveld** [comment]
Hey @yolijn dat je wel!
Wow, fantastisch, wat een heldere en overzichtelijke structuur.
Hiermee wordt alles zoveel makkelijker te onderhouden 🤗 

Op het eerste gezicht heb ik een paar dingen die ik met je wil bespreken.

**Introductiepagina**
Voor de gebruikersvriendelijkheid wil ik graag alle richtlijnen op de introductiepagina vermelden bij de opzet.
Dus: 
- Autocomplete
- Buttons
  - Toetsenbord bediening
  - Etc
- Etc

Dan is er een extra manier van navigeren bovenop het zijmenu, en ook goed voor de zoekmachines.

**Relatief pad**
Waarom is het pad relatief voor de richtlijnen in de algemene readme?
`- [Autocomplete](formulieren/autocomplete)`
in plaats van
`- [Autocomplete](/richtlijnen/formulieren/autocomplete)`
Dat doen we nergens in de website en het hoeft ook niet.

**Intropagina per submenu**
Als ik op het pijltje klik om een submenu te openen, in plaats van op het item zelf, mis je de introductiepagina.
Zo bestaat de kans dat gebruikers deze info missen.
Graag zou ik per item ook een submenu-item naar de introductiepagina willen.

**Labels zijmenu voor de richtlijnen**
Ik wil nog even goed nadenken over de labels voor de richtlijnen in het zijmenu. Soms zijn ze wel erg kort en misschien daardoor niet duidelijk en afhankelijk van de context.
Bijvoorbeeld: 'Plaatsing' komt een paar keer voor.
Automatisch versuren gaat juist over niet automatisch versturen.
Ik wil hier nog even goed naar kijken.

**URLs**
Mooi die korte URLS!
Dat geeft ook de mogelijkheid om nog wat aan de titels te sleutelen en ze uniform te maken.
Ik lees ze nog na om te kijken of ze goed de lading dekken. Hoe werkt FragmentRedirect precies?

**Keywords** 
Staat even los van deze PR  maar ik wil het niet vergeten en ook met je bespreken: wat doen we met de keywords, die zijn nu te algemeen en worden die überhaupt voor de richtlijnen en WCAG-pagina's gebruikt?

**Comment by Yolijn** [comment]
Verbeteringen richtlijnen
* overzichtspagina met introductiepagina combineren
* overzichtspagina openen als je op het onderwerp klikt
* de overzichtspagina die je opent is ook zichtbaar in de sidebar en dan geselecteerd als je op het hoofdonderwerp klikt
* uitzoeken Waarom is het pad relatief voor de richtlijnen in de algemene readme?
    - [Autocomplete](formulieren/autocomplete)
    in plaats van
    - [Autocomplete](/richtlijnen/formulieren/autocomplete)
* Autocomplete onder ‘voorkom fouten’. staat er u zo verloren bij, ik denk dat we die onder het item "Voorkom fouten" moet plaatsen, dan is die uitzondering weg.
* Rian gaat kijken naar de teksten van de sidebars en de urls
* Rian gaat keywords toevoegen
