### ISSUE TITLE
Alle componenten hebben een "sketch" afbeelding

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1080]
## Taken

Jeffrey:

- [x] Calendar
- [x] Case card
- [x] Definition list
- [x] Drawer
- [x] Heading group
- [x] Icon
- [x] Language navigation
- [x] Legend

Rozerin:

- [x] Link list
- [x] Navigation bar
- [x] Number badge
- [x] Pre heading
- [x] Progress list
- [x] Status badge
- [x] Sub-heading
- [x] Task list

## Acceptatie-criteria

- Skecht staat in Figma: https://www.figma.com/design/0Y9Tbb373u6QGxGT6mqUnm/NLDS---Doc-website---Afbeeldingen?node-id=606-943
- Afbeelding staat in de GitHub repo
- Afbeelding volgt naming conventions: `componenten_overzicht_{component-id}.svg`, waarbij `{component-id}` is vervangen door de officiele id.
- Afbeelding is aangeleverd als SVG in een pull request voor de `assets` branch in de documentatie repo: https://github.com/nl-design-system/documentatie/tree/assets
- Afbeelding is geconverteerd naar React op een manier dat de kleur aanpast aan de estafettemodel status (@Yolijn)
- Afbeelding is ingevuld in de mdx file: `export const illustration = "ParagraphSketch";` bijvoorbeeld. Elke component heeft een eigen `index.mdx` file, bijvoorbeeld die van Paragraph: https://github.com/nl-design-system/documentatie/blob/main/docs/componenten/paragraph/index.mdx

## Testen

- Alle cards in het [component overzicht op de website](https://nldesignsystem.nl/componenten/) hebben een afbeelding

**Comment by Rozerinay** [comment]
Links naar de sketches in de assets branch:

-  [Link list](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_link-list.svg)
-  [Navigation bar](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_navigation-bar.svg)
-  [Number badge](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_number-badge.svg)
-  [Pre heading](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_pre-heading.svg)
-  [Progress list](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_progress-list.svg)
-  [Status badge](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_status-badge.svg)
-  [Sub-heading](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_sub-heading.svg)
-  [Task list](https://github.com/nl-design-system/documentatie/blob/assets/componenten_overzicht_task-list.svg)
