### ISSUE TITLE
Design Open Hour: nieuwe calendar afspraak en Slack huddle op website

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1081]
## Acceptatie-criteria

- Designers kunnen gemakkelijk de designer open hour in hun calendar krijgen zodat ze een reminder krijgen op de dag zelf
- De informatie over de nieuwe manier van organiseren (Hudlde in Slack) staat op de website onder "Community" ➝ "Events"
- Er is informatie hoe mensen zich op Slack kunnen aanmelden (kan met linkje naar elders op de site) zodat mensen zich van te voren kunnen aanmelden, in plaats van de ze er op het laatste moment achter komen
- In de calendar invite staat een linkje naar de website in de notitie, zodat mensen nieuwe informatie kunnen vinden als iets het niet doet of als de calendar invite outdatet is

## Testen

Vragen aan mensen of ze vanaf de website de calendar invite kunnen toevoegen, en of het ze dan lukt de huddle te joinen.

**Comment by hidde** [comment]
deze dingen gebeuren al in https://github.com/nl-design-system/kernteam/issues/817, in overleg het issue naar mijn naam gezet, zal na afronding dubbelchecken of we aan deze acceptatiecriteria voldoen

**Comment by hidde** [comment]
Dit alles zit in https://github.com/nl-design-system/documentatie/pull/1174

Bij 'makkelijk op de site te vinden' gekozen om pas link naar Huddle te tonen na aanmelden; kan evt ook direct, graag comment in PR of hier als dat gewenst is.

**Comment by hidde** [comment]
Is nu live!
