### ISSUE TITLE
WCAG-pagina's: issues aanmaken voor TLDR sectie toevoegen voor alle AAA WCAG pagina's

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1213]
Issues aanmaken, vergelijkbaar met de huidige A en AA issues.

Dit zijn:

- [x] 1.2.6 Sign Language (Prerecorded)
- [x] 1.2.7 Extended Audio Description (Prerecorded)
- [x] 1.2.8 Media Alternative (Prerecorded)
- [x] 1.2.9 Audio-only (Live)
- [x] 1.3.6 Identify Purpose (Added in 2.1)
- [x] 1.4.6 Contrast (Enhanced)
- [x] 1.4.7 Low or No Background Audio
- [x] 1.4.8 Visual Presentation
- [x] 1.4.9 Images of Text (No Exception)
- [x] 2.1.3 Keyboard (No Exception)
- [x] 2.2.3 No Timing
- [x] 2.2.4 Interruptions
- [x] 2.2.5 Re-authenticating
- [x] 2.2.6 Timeouts (Added in 2.1)
- [x] 2.3.2 Three Flashes
- [x] 2.3.3 Animation from Interactions (Added in 2.1)
- [x] 2.4.8 Location
- [x] 2.4.9 Link Purpose (Link Only)
- [x] 2.4.10 Section Headings
- [x] 2.4.12 Focus Not Obscured (Enhanced)
- [x] 2.4.13 Focus Appearance
- [x] 2.5.5 Target Size (Enhanced) (Added in 2.1)
- [x] 2.5.6 Concurrent Input Mechanisms (Added in 2.1)
- [x] 3.1.3 Unusual Words
- [x] 3.1.4 Abbreviations
- [x] 3.1.5 Reading Level
- [x] 3.1.6 Pronunciation
- [x] 3.2.5 Change on Request
- [x] 3.3.5 Help
- [x] 3.3.6 Error Prevention (All)
- [x] 3.3.9 Accessible Authentication (Enhanced)

**Comment by rianrietveld** [comment]
@Robbert Issues zijn aangemaakt.
