### ISSUE TITLE
Patronen formulieren nalopen en checken of ze voldoen aan formulier-richtlijnen

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1220]
De [Patronen voor formulieren](https://nldesignsystem.nl/voorbeelden/patronen/formulieren) zijn geschreven voordat we de formulier richtlijnen hadden (november 2023?). We moeten controleren of de adviezen in lijn zijn met de richtlijnen.

## Acceptatie-criteria

- Alle pagina's zijn gecheckt
- Als er problemen zijn, dan wordt er pagina een GitHub Issue aangemaakt.

De problemen hoeven niet opgelost worden. Dat kan bijvoorbeeld later, wanneer we Template pagina's gaan aanbieden.

**Comment by rianrietveld** [comment]
De volgende pagina's zijn gecheckt
- [ ] Meerstappenformulier.
- [ ] Startpunt van een meerstappenformulier.
- [ ] Intropagina van een meerstappenformulier.
- [ ] Inloggen binnen een meerstappenformulier.
- [ ] Stapelen en uitlijnen van een formulier.
- [ ] Markeren van niet verplichte velden.
- [ ] Foutmeldingen in een formulier.
- [ ] Uploaden.
- [ ] Voortgang indicatie binnen een meerstappenformulier.
- [ ] Volgende stap actie.
- [ ] Opslaan of stoppen binnen een meerstappenformulier.
- [ ] Terug navigeren binnen een meerstappenformulier.
- [ ] Funnel header boven een meerstappenformulier.


**Checken:**


- Sommige links naar de richtlijnen kunnen per patrooon specifieker, nu zijn er links naar de [formulierenrichtlijnen](https://nldesignsystem.nl/richtlijnen/formulieren. Bijvoorbeeld: we hebben een pagina met [richtlijnen over meer stappen](https://nldesignsystem.nl/richtlijnen/formulieren/meerdere-stappen/). Daar kunnen we rechtstreeks naar linken bij het [meerstappen-patroon](https://nldesignsystem.nl/voorbeelden/patronen/formulieren/meerstappenformulier).
- Er zijn verouderde links naar de fomulierpagina's, zoals op https://nldesignsystem.nl/voorbeelden/patronen/formulieren/intropagina.
Zie PR https://github.com/nl-design-system/documentatie/pull/1327 met de aanpassingen. Alvast gedaan omdat geboken links echt een bug zijn en geen discussie vergen.

**Gelijktrekken met richtlijnen:**
1: Bij [Markeren van niet verplichte velden](https://nldesignsystem.nl/voorbeelden/patronen/formulieren/niet-verplichte-velden) staat de tekst 

> Wekt de term 'Niet verplicht' (wel b1) andere verwachtingen als de aanduiding 'Optioneel' (niet b1)?

2: Bij de richtlijnen zeggen we specifiek dat 'Optioneel' geen goede tekst is. 

> Let op: Het woord 'optioneel' kan te moeilijk zijn voor mensen die laaggeletterd zijn. Gebruik dus 'niet verplicht'.

3: Consequente naamgeving: we gebruiken bij de richtlijnen "button" en bij de patronen "knop". 'Alert' bovenaan ipv samenvatting van de fouten boven het formulier.

4: Voortgang indicatie binnen een meerstappenformulier
https://nldesignsystem.nl/voorbeelden/patronen/formulieren/voortgang-indicatie
Stappenindicator onder de H2 heading inplaats van erboven.. 
Er staat nu ook bij de bevindingen:
> Vrijwel alle respondenten zien de voortgangs indicatie in eerste instantie over het hoofd. 

Zie ooo bij het kopje "Verder onderzoeken".

**Voorstel voor richtlijn:**

Upladen bestand:
> Het uploaden zelf is nog niet uitgewerkt. We leren graag welke wat de beste manier is om het uploaden van bestanden weer te geven. Inclusief het kunnen verwijderen en foutmeldingen. Dit geldt ook voor de controlepagina. Wat is de beste manier om bestanden, die zijn geupload, hier weer te geven?

**Aanvullend onderzoek:**
Bij [Opslaan of stoppen binnen een meerstappenformulier](https://nldesignsystem.nl/voorbeelden/patronen/formulieren/opslaan-of-stoppen).
Ik zou heel graag aanvullend gebruikersonderzoek willen doen met volledig blinde screenreader gebruikers, hoe het beste aan te geven dat er nog meer keuzes komen na de submitbutton (opslaan/stoppen)/

**Comment by hidde** [comment]
Hidde reviewen

**Comment by hidde** [comment]
Ik heb hier op dit moment geen commentaar op, het klinkt logisch allemaal.
