### ISSUE TITLE
Aanpassingen in de tekst van WCAG-succescriterium 1.1.1 Niet-tekstuele content

### ISSUE THREAD

**Issue by StudioVDS** [nl-design-system/documentatie#1529]
Mogelijke verbeteringen:
- Bij het tweede lijstitem bij Alternatieve teksten op afbeeldingen zou ik niet het woord **doel** gebruiken. Omdat dit al gebruikt wordt bij interactieve elementen zoals links. Ik zou hier gaan voor **informatie** of **relevante informatie**.
- Bij Alternatieve teksten voor video en audio staat nu informatie over ondertiteling, transcript en audiodescriptie. Dit valt allemaal niet onder dit SC. Wat hier wel moet staan is dat er een tekstalternatief aangeboden moet worden voor de video/audio zodat de bezoeker weet waar de video/audio over gaat voor de video afgespeeld wordt. Dit kan als `title` in een `iframe` bij een embed vanuit Youtube. Of door het te beschrijven in de tekst voor de video of moet blijken uit de paginatitel.
- Eventueel bij Controleer voor afbeeldingen in links en buttons nog melden dat als de afbeelding informatief is deze als zodanig gemarkeerd moet worden.
- Bij Check voor afbeeldingen staat: de alt-tekst kan worden leeg gelaten als de betekenis van de afbeelding vlak bij de afbeelding staat. Ik zou hier van maken: het **alt-attribuut** kan worden leeg gelaten als de betekenis van de afbeelding vlak bij de afbeelding **in tekst** staat. Wat ik hier niet zeker weet is of het een kan of een moet is. Is het een optie of is het eigenlijk best practice om hem dan leeg te laten? Anders zou ik er van maken: laat het alt-attribuut leeg als de betekenis van de afbeelding vlak bij de afbeelding **in tekst** staat.

**Comment by rianrietveld** [comment]
@StudioVDS Dank  voor je feedback! Ik ga ernaar kijken.

**Comment by rianrietveld** [comment]
Hoi @StudioVDS 
Ik ben samen met @MarjonBakker door jouw opmerkingen gegaan en hierbij onze feedback

Jouw opmerking: Bij het tweede lijstitem bij Alternatieve teksten op afbeeldingen zou ik niet het woord doel gebruiken.
Ons antwoord: Het doel staat hier met redenen. De alt tekst voor dezelfde een afbeelding kan verschillend zijn als een afbeelding in een andere context wordt gebruikt. Dan is echt het doel belangrijker dat wat er op de afbeelding staat.
Dit hebik beschreven in de blogpost The perfect link bij het kopje "[Embedding an image in a link](https://www.a11y-collective.com/blog/the-perfect-link/#h-embedding-an-image-in-a-link)"
We laten het zo staan.

Jouw opmerking: Bij Alternatieve teksten voor video en audio staat nu informatie over ondertiteling, transcript en audiodescriptie. Dit valt allemaal niet onder dit SC.
Ons antwoord: Ja, inderdaad, je hebt gelijk. Ik zal de tekst aanpassen

Jouw opmerking: Eventueel bij Controleer voor afbeeldingen in links en buttons nog melden dat als de afbeelding informatief is deze als zodanig gemarkeerd moet worden.
Ons antwoord: Goed idee! Dat mist nog inderdaad.

Jouw opmerking: Bij Check voor afbeeldingen staat: de alt-tekst kan worden leeg gelaten als de betekenis van de afbeelding vlak bij de afbeelding staat [...].
Ons antwoord: Ik ga dat beter toelichten in de tekst, want hier bestaat veel verwarring over.

**Comment by Robbert** [comment]
@StudioVDS @rianrietveld We moeten denk ik niet `title` voor `iframe` adviseren, want die zorgt voor een onwenselijke tooltip. `aria-label` is waarschijnlijk beter.

**Comment by StudioVDS** [comment]
Via youtube is het volgens mij standaard een title daar kan je niet veel aan veranderen. En waarom is de tooltip niet wenselijk?

**Comment by rianrietveld** [comment]
Ik wilde morgen pas antwoorden, but anyhow hier is mijn alvast mening:
Het title attribuut is gebruikelijk bij iframes. En ik zou dat ook zo willen houden :-)

**Comment by rianrietveld** [comment]
Gerelateerd over alt tekst.: Een alt test toevoegen voor een afbeelding die decroatief is leidt niet tot afkeuring.
Als bron toevoegen, de post van Leonie Waton https://tink.uk/text-descriptions-emotion-rich-images/

**Comment by rianrietveld** [comment]
@StudioVDS De aanpasisngen zijn doorgevoerd. Bedankt voor je feedback 🙏
