### ISSUE TITLE
Leg acceptatiecriteria uit 

### ISSUE THREAD

**Issue by hidde** [nl-design-system/documentatie#1556]
Ik zou bij componenten onder de kop “Acceptatiecriteria” een korte uitleg van de context verwachten… wat zijn dit voor criteria, en wie gebruikt ze wanneer?

Ik weet niet of we hier al helemaal hetzelfde bij denken, dus ik doe even een voorstel, ik ben benieuwd of dat dan ook klopt met wat anderen in het team (@Rian, @Robbert) denken:

> Gebruik jij één van de implementaties van Button of heb je je eigen Button gemaakt? In beide gevallen geldt: met onderstaande acceptatiecriteria kun je nagaan of jouw gebruik van Button klopt met NL Design System.

Of zeg ik dan iets geks / mis ik nog dingen? Hebben de criteria andere doelen?

Ik zou graag zo'n soort paragraaf toevoegen, zodat mensen die de criteria zien begrijpen waar ze voor zijn.

**Comment by Robbert** [comment]
Deze beschrijving zou onderdeel moeten worden van onze Definition of Done.
