### ISSUE TITLE
.htaccess file wordt niet meer gebruikt sinds nieuwe Plesk instellingen

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/documentatie#1621]
Redirects werken niet meer waardoor

https://nldesignsystem.nl/calendar niet naar https://nldesignsystem.nl/componenten gaat
en https://nldesignsystem.nl/ik-besta-niet niet naar https://nldesignsystem.nl/404.html gaat

**Comment by hidde** [comment]
Yolijn heeft dit opgelost, dotfiles werden niet meegebouwd!
