### ISSUE TITLE
Ruimte tussen ul en p eronder valt weg op de website

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#1729]
Zie bijvoorbeeld bij https://nldesignsystem.nl/wcag/1.1.1/

Als na een unordered list een `p` volgt zit hier geen margin tussen.
![Screenshot van een ul met een p erachter](https://github.com/user-attachments/assets/e1e6ac18-faa1-4071-936f-a5711f51e862)

**Comment by hidde** [comment]
dank, neem ik op in volgende sprint (cc @Yolijn )
