### ISSUE TITLE
docs: Fix toetsenbordfocus bij sluiten zoekmodal

### ISSUE THREAD

**Issue by MarjonBakker** [nl-design-system/documentatie#1733]
Wanneer je met het toetsenbord de zoekfunctie opent door middel van de button 'Start met zoeken' in de main navigation, opent er een modal met een zoekvenster.

Wanneer je de modal sluit door middel van de escape-toets wordt de toetsenbordfocus gereset. De focus is dan weg en wordt op de `body` gezet. 

Plaats de toetsenbordfocus terug op de button die de modal opende.

Button:

```html
<button class="utrecht-button utrecht-button--subtle navbar__item navbar__item--show-on-mobile" type="button" translations="[object Object]" aria-label="Start met zoeken">
  <svg>[...]</svg>
</button>
```

**Comment by hidde** [comment]
Toegevoegd aan komende sprint (cc @Yolijn )
