### ISSUE TITLE
Focus verspringt naar begin van de pagina bij gebruik component-filter-checkbox

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1772]
Op de componentenpagina is een filter die je kan bedienen met checkbox componenten. Als je een van die checkboxen checkt, dan verdwijnt de focus en verspringt die naar het begin van de pagina. Ik zou verwachten dat je daarna kan tabben naar de volgende checkbox.

**Comment by hidde** [comment]
gefixed in https://github.com/nl-design-system/documentatie/pull/1828 🎉
