### ISSUE TITLE
blog post eigen thema maken in themes repository publicabel maken

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/documentatie#302]
- [x] Eerste proef-video is gemaakt gaan we niet publiceren
- [ ] blog post van Hidde op basis van de video op de website publiceren

**Comment by Yolijn** [comment]
Soort blogpost waar Hidde aan begonnen was als basis van documentatie.

Docusaurus heeft een blog functie, die hebben wij niet aan staan, dus we hebben geen blog mapje meer. @Yolijn en @hidde kunnen samen die blog 'aanzetten' en kijken wat er voor styling nog nodig is.

**Comment by hidde** [comment]
ben zo vrij geweest de titel hiervan aan te passen, werkt ie zo voor jou @Yolijn ?

Ik had dit bij refinen niet zo goed voor de bril, maar er is wat verschil tussen blog post en documentatie, en volgens mij gaat deze story over de blog post (mijn draft was geschreven voor het blog, en volgt wat toevallig de volgorde was van de sessie met @Robbert). 

Wat mij betreft doen we deze sprint die blog post, en zorgen we op een later moment dat het onderwerp _theming_ ook formeler en meer voor de eeuwigheid gedocumenteerd is. Die documentatie-versie zou dan ook meer geschreven moeten zijn in dezelfde vorm als de rest van de documentatie.

**Comment by Yolijn** [comment]
Wordt opgepakt als documentatie in plaats van een blogpost https://github.com/nl-design-system/documentatie/issues/499
