### ISSUE TITLE
Expansion Indicators should be triangles not chevrons

### ISSUE THREAD

**Issue by Alkalurops** [nl-design-system/documentatie#362]
These:

<img width="387" alt="" src="https://user-images.githubusercontent.com/1824527/185500213-d5aec11e-724c-461a-96b7-b722855e6f84.png">

might be less confusing, when looking like this:
<img width="322" alt="" src="https://user-images.githubusercontent.com/1824527/185501096-7e31b77e-a2bd-4eff-9674-c568b3d1c49a.png">

otherwise they might be confused with navigation indicators like these

![](https://docs-assets.developer.apple.com/published/83ef757907/navigation_interface_2x_8f059f7f-2e2f-4c86-8468-7402b7b3cfe0.png)
(Example taken from here: https://developer.apple.com/documentation/uikit/uinavigationcontroller).

Thank you for your time.

**Comment by jeffreylauwers** [comment]
Hi Richard, our apologies for the late reaction. Thanks for your suggestion. We have recently updated [our documentation website](https://www.nldesignsystem.nl/). This also includes the side navigation. The chevron icons now point downwards when a second layer of navigation items is present. And will point up when this part is expanded. You could describe it as accordion-ish behavior. Ultimately, we also want to do user research on our documentation website as well. We will keep an eye on whether people experience problems with this while navigating.
