### ISSUE TITLE
Audit huidige website

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/documentatie#364]
We hebben een MVP gemaakt met docusaurus componenten gemixt met community componenten en custom componenten. Voordat we allemaal scrutiny krijgen nu we allemaal toegankelijke PR doen is het fijn te weten of er issues zijn. Als we ze vonden kunnen we inschatte met welke prioriteit we die moeten fixen en publieke issues aanmaken.

De verklaring kan gelijk door naar toegankelijkheidsverklaring.nl, want daar hebben we al uitstel voor gehad.

**Comment by rianrietveld** [comment]
Ik stel voor dat ik hier een WCAG EM audit rapport van maak, met roadmap, zodat we een 
officiële toegankelijkheidsverklaring kunnen aanmaken. Ter referentie voor op de pagina [Toegabnkelijkhiedsverklaring](https://nldesignsystem.nl/toegankelijkheidsverklaring) op onze site.

**Comment by hidde** [comment]
Lijkt mij een goed idee @rianrietveld !

**Comment by hidde** [comment]
Naar Done! We hebben 'm vandaag doorsproken, met de WCAG-EM report generator een HTML rapport gemaakt en die op de site geplaatst.
