### ISSUE TITLE
Afbeeldingen teamleden hebben geen alternatief (oplossing H: markeer svgs als decoratief?)

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#379]
Zie pagina https://nldesignsystem.nl/project/kernteam

**Comment by rianrietveld** [comment]
Mee eens:
`aria-hidden="true"` op het SVG element zetten

**Comment by Yolijn** [comment]
We hebben geen afbeeldingen van teamleden meer op de website. Lekker makkelijk, kan deze dicht :)
