### ISSUE TITLE
Kleuren code-blokken html hetzelfde maken als kleuren code-blokken guideline

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#394]

**Comment by hidde** [comment]
de HTML codeblokken zijn door Docusaurus geprocesste Markdown, die gethemed worden met Prism.

De kleuren staan in: https://github.com/nl-design-system/documentatie/blob/main/src/components/Canvas/PrismStyle.ts

We zouden in [de config](https://github.com/nl-design-system/documentatie/blob/main/docusaurus.config.js ) [`prism: [theme]` moeten toevoegen](https://docusaurus.io/docs/markdown-features/code-blocks#theming), waarbij `theme.plain` een object is zoals in `PrismStyle`.
