### ISSUE TITLE
Placeholder zoekveld heeft onvoldoende contrast (<4.5:1)

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#412]

**Comment by hidde** [comment]
We gaan het zoekcomponent [vervangen door eentje uit de community](https://github.com/nl-design-system/documentatie/issues/1617), dan is dit issue wsl moot.

**Comment by hidde** [comment]
MVP kunnen we om dit issue op te lossen `--docsearch-muted-color` aanpassen in custom.css, zodat het voldoende contrast heeft.
