### ISSUE TITLE
Waarschuw bij openen nieuwe tab in een link

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#420]
In de footer staan een aantal links. Sommige openen in een nieuw venster andere niet. Voor screen reader usability is het bijzonder fijn als daar een melding van komt. En omdat alle gebruikers dezelfde info moeten krijgen is een icoontje bij de links naar een nieuwe tab wenselijk.

**Comment by hidde** [comment]
Besproken in Amersfoort… we gaan geen extra toevoeging doen voor screenreaders of sighted users, want meer de verantwoordelijkheid van browsers/screenreaders, niet zo zinvol om op onze eigen site te doen; plus het zou in de weg zitten als screenreaders ineens wel gaan herkennen dat er een `target` attribuut is.
