### ISSUE TITLE
Het actieve menu item is alleen aangegeven met een gekleurd balkje en niet met aria-current.

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#424]

**Comment by hidde** [comment]
Deze is inmiddels _bijna_ opgelost, alle menu items hebben een aria-current=page, behalve bij `Voorbeelden`. Even dubbelchecken in `sidebarConfig.ts` en `navConfig.ts` en verschillen tussen community en voorbeelden.

**Comment by hidde** [comment]
“Voorbeelden” opzetten zoals richtlijnen van formulieren, waar de overzichtspagina  het `OverviewPage` component gebruikt, dan kunnen we ook makkelijker extra tekst erop hebben en dat fixt mogelijk dit issue ook. Maak dan de pagina die je ziet als de README van Voorbeelden.

**Comment by hidde** [comment]
dit was gisteren gefixed door @Yolijn in https://github.com/nl-design-system/documentatie/pull/1626 🎉 !
