### ISSUE TITLE
Algemeen e-mailadres is visueel verborgen

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#425]
Op de pagina https://nldesignsystem.nl/project/kernteam staat het algemene e-mailadres (nldesignsystem@gebruikercentraal.nl) visueel verborgen:   
[Neem contact op](mailto:nldesignsystem@gebruikercentraal.nl).

Voorstel tekst:   
Neem contact op door een e-mail te sturen naar [nldesignsystem@gebruikercentraal.nl](mailto:nldesignsystem@gebruikercentraal.nl)

**Comment by hidde** [comment]
Is dit niet reeds gedaan?

**Comment by Robbert** [comment]
Done! ✔️
