### ISSUE TITLE
Anchors bij headings toevoegen zodat deeplinken makkelijker wordt

### ISSUE THREAD

**Issue by hidde** [nl-design-system/documentatie#427]
(in ieder geval bij richtlijnen, wellicht bij alle content?)

**Comment by rianrietveld** [comment]
@hidde Ik denk dat we het submenu moeten repareren voor deze veergaves, het werkt wel bij de andere pagina's maar niet bij deze nieuwe richtlijnen. Dan heb je automatisch de linkjes.

**Comment by rianrietveld** [comment]
Gerelateerd: 
https://github.com/nl-design-system/documentatie/issues/606

**Comment by hidde** [comment]
Niet meer relevant! thanks @rianrietveld voor oplettendheid
