### ISSUE TITLE
Blocking CSS/Guideline issues documentatie site

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#439]
Plaats hier 
- CSS problemen in nldesignsystem.nl, die niet makkelijk via de bestaande CSS zijn op te lossen.
- Weergave problemen met de Guideline component

**Comment by rianrietveld** [comment]
@Robbert na de laaste grote update is de weergave van codevoorbeelden niet goed meer.
In de custom.css had @Hidde styling toegevoegd voor losse code blokken bij de tekst.

Die refereren naar:
`code[class*="language-"]` en `pre[class*="language-"]`
Beide classes bestaan nu niet meer.

Zie bijvoorbeeld op: https://nldesignsystem.nl/richtlijnen/formulieren/alle-richtlijnen/labels/

![screenshot van code, nu niet meer opgemaakt maar in zwart/wit](https://github.com/nl-design-system/documentatie/assets/2351479/e6793319-da3e-4f62-bef6-1c9985042650)

**Comment by rianrietveld** [comment]
De JS events `onpaste` en `ondrop` op het input veld worden verwijderd bij het genereren van de component-weergave.
```
<Guideline appearance="dont" title="Blokkeer kopiëren van een nieuw wachtwoord.">
  <Canvas language="html">
    {() => (
      <>
        <label for="pw2">Uw nieuwe wachtwoord</label>
        <input type="password" id="pw2" onpaste="return false;" ondrop="return false;" autocomplete="off"  name="wachtwoord" />
      </>
    )}
  </Canvas>
</Guideline>
```

**Comment by Robbert** [comment]
Alleen de onPaste issue moet nog.

**Comment by hidde** [comment]
Deze is op dit moment geen probleem meer want voorbeeld staat [niet meer op de pagina Wachtwoord plakken](https://nldesignsystem.nl/richtlijnen/formulieren/voorkom-fouten/wachtwoord-plakken/).
