### ISSUE TITLE
Documentatie over thema maken uitbreiden

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/documentatie#499]
Er is nu alleen een video bij https://nldesignsystem.nl/meedoen/als-developer/thema-maken. Hidde heeft op basis van de sessie die Robbert met Conduction had een blog neergezet. Die is niet gepubliceerd en hij is eigenlijk juist geschikt als mvp documentatie naast de video.

**Comment by hidde** [comment]
Voorstel hiervoor in https://github.com/nl-design-system/documentatie/pull/547

**Comment by hidde** [comment]
Deze terug de sprint in getrokken want ontdekte dat ik het nooit meer gemerged had gekregen, staat nu alsnog klaar voor merge in #547
