### ISSUE TITLE
Nalopen: formulierrichtlijnen en links naar WCAG

### ISSUE THREAD

**Issue by hidde** [nl-design-system/documentatie#545]
Ik zie dat we soms naar Nederlands (WCAG), soms naar Engels (Understanding) en die laatste soms naar 2.1 en soms naar 2.2 gaan, dus die zouden we nog ff moeten nalopen en slimme keuze maken.

**Comment by Robbert** [comment]
Ik zou graag linken naar bijvoorbeeld: `https://nldesignsystem/wcag2/1.3.5`, vanwaar we kunnen linken naar diverse dingen:

- de Engelse WCAG pagina
- de Nederlandse WCAG pagina
- de pagina's in ons design system die gerelateerde tips hebben

**Comment by rianrietveld** [comment]
Gerelateerd: #561

**Comment by rianrietveld** [comment]
Dit issue is een duplicate van #561 
Comments bij dat issue overgenomen.
