### ISSUE TITLE
Richtlijn “meerdere stappen”: informatie over forms mode beter organiseren

### ISSUE THREAD

**Issue by hidde** [nl-design-system/documentatie#582]
@Robbert stelde voor informatie over form mode in “meerdere stappen” deels te verhuizen naar “descriptions”, want geldt niet alleen voor multistep-forms.

@rianrietveld suggereerde: 

> Voorstel:
> heb je uitgebreide info nodig bij een stuk: maak er een multisstep form van: om tekst goed te laten voorlezen (buiten het formulier).
> Bij bij descriptions: vertellen waarom want form mode en JAWS.

**Comment by rianrietveld** [comment]
PR staat op: https://github.com/nl-design-system/documentatie/pull/609
