### ISSUE TITLE
Heartbeat videos URL kapot na refreshen

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#593]
Steps to reproduce:
1. https://www.nldesignsystem.nl/events/heartbeat
2. ga naar video's
3. je bent dan op [1. https://www.nldesignsystem.nl/community/events/ video](https://www.nldesignsystem.nl/events/heartbeat/videos)
4. reload
5. ERROR

**Comment by matijs** [comment]
1. Vanaf [heartbeat overzicht](https://www.nldesignsystem.nl/events/heartbeat/overzicht) door naar [video's](https://www.nldesignsystem.nl/events/heartbeat/videos)
2. Video's laden heel langzaam. De URL is https://www.nldesignsystem.nl/events/heartbeat/videos
3. Reload, dit resulteert in een 403 en de URL is: https://www.nldesignsystem.nl/community/events/
