### ISSUE TITLE
Blogpost: Foutmeldingen

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#613]
Draft: https://docs.google.com/document/d/1WhIOX_7Ha6txAFkpa_xC6ZK0nEyiI_R0fTdM9C-x6pU/

**Comment by Robbert** [comment]
Ik zou graag wel duidelijk maken dat het `required` attribuut niet verboden is voor websites die geen JavaScript gebruiken om het formulier te valideren. Formulieren die browser-validatie hebben en daarna server-side validatie, die kunnen maar beter wel `required` gebruiken.

Bijvoorbeeld: als je op een langzame internetverbinding zit, dan kan het heel onhandig zijn als je niet op tijd wordt gewaarschuwd dat je iets niet hebt ingevuld.

**Comment by rianrietveld** [comment]
@robbert, @hidde 
Ik heb besloten hier 2 blogposts van te maken, één algemeen die de richtlijnen aan elkaar knoopt qua foutmeldingen en één die technisch op aria-required en required en het gebruik van de summary ingaat. Dan is het een beter verhaal samen.

**Comment by rianrietveld** [comment]
@Robbert 

Ik heb het volgende voorstel.
De richtlijn  [Gebruik geen HTML-formuliervalidatie](https://nldesignsystem.nl/richtlijnen/formulieren/foutmeldingen#gebruik-geen-html-formuliervalidatie) pas ik als volgt aan:

## Gebruik geen HTML-formuliervalidatie
 [... huidige tekst ...]

### Progressive enhancement
Alhoewel we HTML-formuliervalidatie afraden en niet als eindoplossing zien, kan het nuttig zijn om te gebruiken als fallback bij een slechte internetverbinding als er nog geen JavaScript beschikbaar is.

Deze optie geldt alleen voor formulieren waarbij de foutmeldingen worden afgehandeld door JavaScript. 

De opzet is dan als volgt:
- Bij de formuliervelden wordt het attribuut `required` gebruikt in plaats van 'aria-required'.
- Zodra de JavaScript wordt ingeladen wordt ook het attribuut `novalidate` toegevoegd aan het `<form>` element om de HTML-validatie uit te schakelen.

Dan voorkom je dat gebruikers met een slechte internetverbinding niet op tijd worden geïnformeerd over fouten in het formulier.

Dit is een optie en geen vereiste. Uiteindelijk is een op maat gemaakte eind-validatie van de formuliervelden het meest betrouwbaar en toegankelijk en daardoor de richtlijn.

**Comment by rianrietveld** [comment]
Ik heb over de inhoud nagedacht en ik denk dat een supertechnisch verhaal niet thuishoort in een blog.
Beter is om dit toe te voegen aan de richtlijnen en later aan ons storybook bij de componenten.

Wat ik nu heb gedaan is een verhaal schrijven die in een logisch verhaal de richtlijnen voor foutmeldingen aan elkaar knoopt. Een link naar deze post kan bij de intro van de forulier-richtlijnen worden gezet.

Draft: https://docs.google.com/document/d/1WhIOX_7Ha6txAFkpa_xC6ZK0nEyiI_R0fTdM9C-x6pU/

**Comment by hidde** [comment]
@rianrietveld  Mooie blog post geworden zo! Heb nog een aantal suggesties en opmerkingen toegevoegd, wmb kunnen we nadat je naar de opmerkingen hebt kunnen kijken snel publiceren. Ik zet 'm weer terug op jouw naam.
