### ISSUE TITLE
WCAG-pagina Succescriterium 2.4.13 Focusweergave

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#628]
Pagina schrijven voor WCAG Succescriterium 2.4.13 Focusweergave.
Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/561

Inhoud:
- W3C referenties
- Korte samenvatting
- Gerelateerde NL Design System-richtlijnen
- Bronnen
- Gebruikersonderzoek
- Hoe te testen

**Comment by rianrietveld** [comment]
Veel voorbeelden erbij

**Comment by Robbert** [comment]
Voorbeeld van berekening (work in progress!) van focus outline area. https://frameless.studio/design/focus-indicator
Dingen die nog ontbreken uit de berekening:
- achtergrondkleur container contrast ratio
- achtergrondkleur button contrast ratio
- border color contrast ratio
- box-shadow ring oppervlakte meetellen en contrast ratio berekenen
