### ISSUE TITLE
Teveel = te veel

### ISSUE THREAD

**Issue by sanmai-NL** [nl-design-system/documentatie#63]
Volgens mij staan jullie niet toe om te forken en een PR te maken. Hierbij een issue over een taalfout.

**Comment by usethetics** [comment]
> Volgens mij staan jullie niet toe om te forken en een PR te maken. Hierbij een issue over een taalfout.

Ik kwam deze taalfout op twee plaatsen in de tekst over iconografie tegen, klopt dat? Ik heb deze gewijzigd.

Als het goed is zou het overigens mogelijk moeten zijn om een fork te maken.
