### ISSUE TITLE
WCAG-pagina 2.4.1 Blokken omzeilen

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#654]
Pagina schrijven voor WCAG Succescriterium 2.4.1 Blokken omzeilen
Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/561

Inhoud:
- W3C referenties
- Korte samenvatting
- Gerelateerde NL Design System-richtlijnen
- Bronnen
- Gebruikersonderzoek
- Hoe te testen

**Comment by hidde** [comment]
Ik heb hier zojuist alles gesloten wat gesloten kon worden, er staan nog een paar dingen open waar Rian nog een keuze in kan maken wat ermee te doen.
