### ISSUE TITLE
WCAG-pagina 2.4.6 Koppen en labels

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#659]
Pagina schrijven voor WCAG Succescriterium 2.4.6 Koppen en labels
Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/561
PR: #930 
Preview: https://documentatie-git-wcag-2-4-6-koppen-en-labels-nl-design-system.vercel.app/wcag/2.4.6

**Comment by hidde** [comment]
Ik heb een paar kleine puntjes toegevoegd en al geapproved. Ik geef 'm hierbij terug aan jou @rianrietveld, dan kun je er evt nog naar kijken en als je 'm dan goed vind kunnen we wmb mergen.
