### ISSUE TITLE
Aanpassing WCAG-pagina 1.1.1 Niet-tekstuele content

### ISSUE THREAD

**Issue by StudioVDS** [nl-design-system/documentatie#692]
Hoi @rianrietveld,
Zoals gezegd een eerste opmerking op de WCAG pagina's.
Bij het onderdeel Alternatieve teksten op afbeeldingen staan de bullets:

- als een afbeelding decoratief is, moet de alt-tekst leeg zijn.
- de alt-tekst kan worden leeg gelaten als de betekenis van de afbeelding vlak bij de afbeelding staat.

Ik zou hier van maken dat het alt-attribuut leeg moet zijn niet de alt-tekst.

Verder misschien nog een bullet toevoegen om duidelijk te maken dat een tekst in een afbeelding, zoals bij een logo, altijd volledig overgenomen moet worden in de alt-tekst.

**Comment by rianrietveld** [comment]
@StudioVDS Dank voor de aanpassing! We gaan het inplannen.
