### ISSUE TITLE
Website: Maak de 404 pagina van de website betekenisvol

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#737]
De huidige 404 pagina is Engelstalig en geeft onduidelijke en onvoldoende informatie.
Zie: https://nldesignsystem.nl/onzin

Huidige info:
```
Server Error 404 Page Not Found
This page either doesn't exist, or it moved somewhere else.
That's what you can do
[Reload Page](javascript:location.reload();) 
[Back to Previous Page](javascript:history.back();) 
[Home Page](https://nldesignsystem.nl/)
```

ZIe screen shot:
![Screenshot 2024-03-18 at 11 29 14](https://github.com/nl-design-system/documentatie/assets/2351479/fc386a98-37fb-43e9-a235-2a7e0462e3f3)

Een eigen (Nederlandstalig) 404 pagina is nodig.

Good practice voor een 404 pagina:
- Vermijd het woord 404, maar zeg dat de pagina niet gevonden is.
- Geef een link naar de voorpagina, verwijs naar de zoekoptie.
- Zeg waar mensen een fout kunnen melden (link naar contact oi.)

Bijvoorbeeld:
Pagina niet gevonden
De pagina die je wilt bezoeken bestaat niet (meer). Maar we hebben wat tips voor je om alsnog te vinden wat je zoekt:
- Start bij de [voorpagina](https://nldesignsystem.nl/).
- Gebruik het menu bovenin.
- Gebruik de zoekoptie in de menubalk.

Denk je dat het een fout in de website is? Meld ons de gebroken link alsjeblieft door een e-mail te sturen naar [kernteam@nldesignsystem.nl](mailto:kernteam@nldesignsystem.nl).

**Comment by Yolijn** [comment]
We maken nu gebruik van de 404 pagina van Docusaurus. Die is in de pagina en heeft een duidelijkere melding. 

Extra bonus punten om deze pagina nog duidelijker te maken kunnen we halen door

- [ ] De teksten op die pagina kunnen we een andere beschrijving geven in de vertaling met het [toevoegen van de i18N vertaling](https://docusaurus.io/docs/i18n/tutorial#single-domain-deployment) `pnpm run write-translations --locale nl`
- [ ] Het Docusaurus component `NotFound` te [Swizzle-en](https://docusaurus.io/docs/swizzling)

**Comment by hidde** [comment]
Dit is opgelost, echter is het nu stuk omdat de htaccess niet wordt gelezen, dat gaan we deze sprint oplossen.

**Comment by hidde** [comment]
dit is gisteren gefixed in https://github.com/nl-design-system/documentatie/pull/1625
