### ISSUE TITLE
Richtlijnen: is het nog essentieel om alle niet form-control gerelateerde info buiten het formulier te houden

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#750]
Naar aanleiding van interne discussies:
Is het essentieel dat informatie, die niet gekoppeld is aan een form control boven (buiten) het formulier staat.
Als praktisch voorbeeld: Moet de summery van foutmeldingen echt boven het formulier staan of kan het ook binnen het `<form >`-element staan.

Dit in verband met het goed voorlezen van de informatie met screenreaders in Form Mode.
Op dit moment keurt Swink hier niet meer op of.

Gerelateerde richtlijn:
[Samenvatting boven het formulier](https://nldesignsystem.nl/richtlijnen/formulieren/foutmeldingen/#zet-een-samenvatting-van-de-foutmeldingen-boven-het-formulier)

Volgens: [[Form Instructions - WAI Web Accessibility Tutorials](https://www.w3.org/WAI/EO/Drafts/tutorials/forms/instructions/)](https://www.w3.org/WAI/tutorials/forms/instructions/)
> Important: Screen readers often switch to “Forms Mode” when they are processing content within a `<form>` element. In this mode they usually only read aloud form elements such as `<input>`, `<select>`, `<textarea>`, `<legend>`, and `<label>`. It is critical to include form instructions in ways that can be read aloud. This will be explained further below.

**Comment by Robbert** [comment]
Zou sowieso heel fijn zijn om een videootje te hebben (a11y hidde?) van waarom dit echt zo belangrijk is. Fail video :)

**Comment by Robbert** [comment]
Laat na overleg met at-julesrulez even weten wat de uitkomst is, zodat de Figma designs kloppend gemaakt worden #627

**Comment by rianrietveld** [comment]
@jeffreylauwers @Robbert @hidde 

Na overleg met Jules, ik denk dat we op een lijn zitten qua wat er los aan tekst in een formulier (as in`<form>[...]</form>`) kan en wat niet. 
- Belangrijke info erboven of gekoppeld in een description.
- Eventuele kopjes om de boel te verdelen kan wel, maar liever in een fieldset legend opgemaakt als kopje.

Maar het is belangrijk dit goed op te schrijven. Daarom heb ik het volgende voorstel:
- We (@jeffreylauwers en ik) schrijven richtlijn over wat er aan losse tekst/kopjes kan in een formuleir en wat er boven moet. 
- Hierbij geven we veel voorbeelden met wat goed en fout is. Toepasbaar in de Figna designs.
- We checken dit bij @julezrulez, of dit goedgekeurd gaat worden.
- We publiceren dit bij de formulierrichtlijnen.

Waar we het ook over eens waren:
Eigenlijk zouden we een gebruikersonderzoek moeten doen met blinde screen reader gebruikers. Met verschillende screen readers en devices. Met verschillende scenarios. Omdat de manier waarop men door een formulier heen gaat belankrijk is. 
Gaat een gebruiker eerst in read mode door het formulier en daarna in form mode?
Of altijd in read mode? Screen readers kunnen zo veel meer tegenwoordig. En we doen nu zoveel aannames.

**Comment by rianrietveld** [comment]
Ik sluit dit issue:
Het werk wordt verder opgepakt in de issues:
- [Testsessie formulieren met blinde screenreadergebruikers #810](https://github.com/nl-design-system/documentatie/issues/810)
- [Richtlijnen: nieuwe richtlijn over wat er aan losse tekst/kopjes kan binnen het form element en wat er boven moet. #830](https://github.com/nl-design-system/documentatie/issues/830)
