### ISSUE TITLE
Richtlijnen: op elke pagina duidelijk vermelden dat de richtlijnen nog in beta zijn.

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#751]
Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/742

Het moet duidelijk zijn op een pagina met richtlijnen wat de status is van de richtlijnen is.
Dus dat ze nog niet in steen gegoten zijn maar dat we graag vanuit de community reactie willen.

Er komt hier eal en verhaal over op de intropagina, maar er moet ook een vermelding komen op de pagina's zelf.
Omdat we nog geen status aan de richtlijnen hebben gegeven, is voor nu een snelle oplossing om tekst aan de footer van elke richtlijnenpagina toe te voegen

Footer tekst nu:
**Aanvullingen of opmerkingen?**
Deze richtlijnen worden onderhouden door het NL Design System. Heb je aanvullingen of opmerkingen? [Deel je mening op GitHub](https://github.com/nl-design-system/documentatie/discussions/473) met je suggesties.

Voorstel nieuwe footertekst:
**Over deze richtlijnen**
Deze richtlijnen worden onderhouden door het NL Design System en zijn op dit moment in 'beta'. 

We willen graag van de community horen of ze werkbaar en nuttig zijn. Heb je aanvullingen of opmerkingen? [Deel je mening op GitHub](https://github.com/nl-design-system/documentatie/discussions/473) met je suggesties.

**Comment by rianrietveld** [comment]
@hidde @robbert, zijn jullie het met de bovenstaande nieuwe tekst in de footer van een richtlijnenpagina eens?

**Comment by hidde** [comment]
Eigenlijk vind ik 'onderhouden door het NL Design System' vaag, is het het kernteam of de community, moeten we dat nog duidelijker maken?

**Comment by rianrietveld** [comment]
@hidde 
Wat dacht je van:

> Deze richtlijnen worden beheerd door het NL Design System in samenwerking met de community,  en zijn op dit moment nog in ontwikkeling.
We willen graag van de community horen of ze werkbaar en nuttig zijn. Heb je aanvullingen of opmerkingen? [Discusieer mee](https://github.com/nl-design-system/documentatie/discussions/473) of [open een nieuw issue](https://github.com/nl-design-system/documentatie/issues).
