### ISSUE TITLE
Responsiveness (op iPhone SE)

### ISSUE THREAD

**Issue by TessaViergever** [nl-design-system/documentatie#766]
Van de week wilde ik op LinkedIn een post van NLDS lezen vanaf mijn iPhone (SE 2020). Dit is hoe ik het blog artikel in beeld kreeg:

<img width="300" src="https://github.com/nl-design-system/documentatie/assets/112861180/6228d1bd-3d1a-4fe2-8864-0201a9bcf502">

Het artikel uitzoomen gaf wel alle content in beeld maar echt lekker leesbaar was de tekst niet. Het voelde voor mij meer of ik op een desktop versie van de website was.
<img width="300" src="https://github.com/nl-design-system/documentatie/assets/112861180/1a5e7267-d8d3-4aac-a5c0-f425e04c1b04">

Toen dacht ik, wellicht gaat het mis bij LinkedIn. Ik heb daarom de website ook nog even vanuit Chrome (versie 123.0.6312.52) geopend op mijn iPhone. Al op de homepage kwam ik hetzelfde tegen als op de blog pagina via LinkedIn.
<img width="300" src="https://github.com/nl-design-system/documentatie/assets/112861180/2e18a5d8-7f6a-48ab-8ae8-bea9e138e19f"> 

Ook het uitzoomen was vergelijkbaar. 
<img width="300" src="https://github.com/nl-design-system/documentatie/assets/112861180/2bb45a10-afab-4abb-91ff-a3c371e2a15b">

Details in de header geven een extra bevestiging dat er ergens iets niet helemaal goed gaat.
<img width="200" src="https://github.com/nl-design-system/documentatie/assets/112861180/b8aa208e-d849-44e9-8507-c6f94ab84146">

**Mogelijke oplossing**

Eerst dacht ik dat er wellicht een media query verkeerd stond maar wanneer ik de website in inspector op iPhone SE zet, lijkt het wel goed te gaan. Dus wellicht dat er een techniek gebruikt die (nog) niet ondersteund wordt door alle apparaten/browsers? In dat geval zou een fallback misschien een oplossing kunnen zijn. 

<img width="438" src="https://github.com/nl-design-system/documentatie/assets/112861180/d6100e5b-37e5-4847-9b77-da989149720d">

**Comment by hidde** [comment]
Hey Tessa, dank voor het doorgeven en de uitgebreide documentatie met screenshots. We gaan het verder onderzoeken.

**Comment by Robbert** [comment]
Bedankt Tessa! De issues die je hebt gevonden hebben afgelopen sprint opgelost, bedankt voor het behartigen van de belangen van de gebruiker 🫶💯
