### ISSUE TITLE
Componenten: Opzet refererende tekst naar WCAG-succescriteria gelijk trekken met de opzet zoals bij de richtlijnen.

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#812]
De wijze waarop naar WCAG-succescriteria wordt verwezen is anders bij de componenten dan bij de richtlijnen.

Bijvoorbeeld bij de [component paragraaf](https://nldesignsystem.nl/paragraph/).
Hier wordt gesproken over WCAG regels en WCAG eis 1.3.1

Deze referentieteksten moeten bij alle componenten worden aangepast zodat ze overeenkomen met wat we bij de richtlijnen doen.
Dus:
- 'Relevante WCAG-succescriteria' ipv 'Relevante WCAG regels'.
- 'WCAG-succescriterium 1.3.1 Info en relaties' ipv 'WCAG eis 1.3.1'.

**Comment by hidde** [comment]
Heel goed idee! En waar we ze al hebben kunnen we dan ook gelijk naar onze WCAG-pagina's linken!

**Comment by rianrietveld** [comment]
Is aangepast met de #1202 (WCAG-pagina's: voegt summary toe aan bestaande WCAG-pagina's en voegt nog ontbrekende nieuwe pagina's toe)
