### ISSUE TITLE
WCAG-pagina's: Verander de tekst van het kopje 'Korte samenvatting' in 'Uitleg'

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#848]
Op de [WCAG-pagina's](https://nldesignsystem.nl/wcag) staat na de W3C referenties het kopje 'Korte samenvatting' van het succescriterium.
Deze samenvatting is niet altijd kort, zeker als er veel voorbeelden bij staan. De tekst 'Uitleg' dekt de lading dan beter.

note to self: ook https://nldesignsystem.nl/wcag/introduction aanpassen

**Comment by hidde** [comment]
Klinkt logisch! 

Andere mogelijkheid is misschien om het bij te lange tekst te splitsen, dus de korte samenvatting eerst, en dan whatever er nog bij moest, zoals voorbeelden. We zouden ook kunnen zorgen dat de eerste paragraaf van de “Uitleg” altijd een soort algemene samenvatting is?

**Comment by hidde** [comment]
Klinkt logisch! 

Andere mogelijkheid is misschien om het bij te lange tekst te splitsen, dus de korte samenvatting eerst, en dan whatever er nog bij moest, zoals voorbeelden. We zouden ook kunnen zorgen dat de eerste paragraaf van de “Uitleg” altijd een soort algemene samenvatting is?

**Comment by rianrietveld** [comment]
@hidde 
Kun je met het ook hierop kijken naar de "korte samenvatting" van de eerste paragraaf van de “Uitleg” altijd een soort algemene samenvatting van https://github.com/nl-design-system/documentatie/pull/851? is dit een goede opzet?
