### ISSUE TITLE
De code van correcte voorbeelden is niet te kopiëren

### ISSUE THREAD

**Issue by alimpens** [nl-design-system/documentatie#885]
De code van correcte voorbeelden bij Richtlijnen is niet te kopiëren.

Om te reproduceren:

- Ga naar een pagina met codevoorbeelden, [zoals deze](https://www.nldesignsystem.nl/richtlijnen/formulieren/voorkom-fouten/)
- Klik op 'Bekijk code' bij het eerste 'Doen' voorbeeld
- Constateer dat je een `not-allowed` cursor te zien krijgt en dat je de code niet kan kopiëren

Context:

Chrome op Windows

**Comment by Robbert** [comment]
https://github.com/nl-design-system/documentatie/blob/main/src/components/Canvas/Canvas.tsx#L63

`copy = false` is denk ik niet de ideale default.

https://github.com/nl-design-system/documentatie/blob/main/docs/richtlijnen/formulieren/_help-show-required-option1-code.mdx?plain=1#L23-L24

Je zou willen dat als <Guideline appearance="dont"> heeft dat de nested `<Canvas>` dan automatisch weet dat die `copy = false` moet doen
