### ISSUE TITLE
WCAG-pagina: 2.4.10 Paragraafkoppen

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#938]
Pagina schrijven voor 2.4.10 Paragraafkoppen
Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/561

**Comment by hidde** [comment]
Heb laatste check op deze PR gedaan en openstaande comments kunnen sluiten nav laatste check. Is nu aan het mergen!
