### ISSUE TITLE
"Breaking changes" voor Figma documenteren

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#997]
Gerelateerd aan de design tokens: #843

Voor Figma designers documenteren welke changes breaking changes, features en patches zijn (major/minor/patch)

**Comment by Rozerinay** [comment]
We gaan dit samen oppakken met Jeffrey, Yolijn, Robbert en Rozerin.

**Comment by Yolijn** [comment]
Doel sprint 22 is om tijdens het maken van allemaal breaking-changes ons proces wat aan het vormen is hier bij te houden in notitie-vorm.

Maken van mooie docs komt later
